// const SERVER_BASE_URL = 'http://localhost:7000/api/v1';
const SERVER_BASE_URL = 'https://goldstar-api.herokuapp.com/api/v1';
const GOLD_STAR_THEME_VARIANT = 'GOLD_STAR_THEME_VARIANT';
const GOLD_STAR_AUTH_TOKEN = 'GOLD_STAR_AUTH_TOKEN';
const GOLD_STAR_AUTH_DATA = 'GOLD_STAR_AUTH_DATA';
const GOLD_STAR_VIEW_MODE = 'GOLD_STAR_VIEW_MODE';

export const CONSTANTS = {SERVER_BASE_URL, GOLD_STAR_THEME_VARIANT, GOLD_STAR_AUTH_TOKEN, GOLD_STAR_AUTH_DATA, GOLD_STAR_VIEW_MODE};
